#encoding: Big5
Adminparam.create(:point_get_feedback => 25, :point_get_pastexam => 60, :point_need_feedback => 0, :point_need_pastexam => 10) unless Adminparam.first
User.create(:username => 'admin', :email => 'admin@gmail.com', :password => '12345678', :password_confirmation => '12345678' , :is_admin => 2, :nick_name => 'admin', :first_name => 'admin', :last_name => 'admin', :rank => 9999999, :maxrank => 9999999) unless User.where(:username => 'admin')
Course.create( :name => '物件導向程式設計', :instructor => '王昱舜', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物件導向程式設計', :instructor => '王昱舜').first
Course.create( :name => '物件導向程式設計', :instructor => '柯皓仁', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物件導向程式設計', :instructor => '柯皓仁').first
Course.create( :name => '物件導向程式設計', :instructor => '荊宇泰', :grade => 1, :description => '大一必修，英文授課' ) unless Course.where(:name => '物件導向程式設計', :instructor => '荊宇泰').first
Course.create( :name => '物件導向程式設計', :instructor => '游逸平', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物件導向程式設計', :instructor => '游逸平').first
Course.create( :name => '物件導向程式設計', :instructor => '黃俊龍', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物件導向程式設計', :instructor => '黃俊龍').first
Course.create( :name => '物件導向程式設計', :instructor => '黃問泙', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物件導向程式設計', :instructor => '黃問泙').first
Course.create( :name => '物件導向程式設計', :instructor => '溫宏斌', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物件導向程式設計', :instructor => '溫宏斌').first
Course.create( :name => '物件導向程式設計', :instructor => '蔡文能', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物件導向程式設計', :instructor => '蔡文能').first
Course.create( :name => '物理(一)', :instructor => '林烜輝', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物理(一)', :instructor => '林烜輝').first
Course.create( :name => '物理(一)', :instructor => '莊振益', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物理(一)', :instructor => '莊振益').first
Course.create( :name => '物理(一)', :instructor => '許世英', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物理(一)', :instructor => '許世英').first
Course.create( :name => '物理(一)', :instructor => '陳文雄', :grade => 1, :description => '大一必修，英文授課' ) unless Course.where(:name => '物理(一)', :instructor => '陳文雄').first
Course.create( :name => '物理(一)', :instructor => '陳永富', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物理(一)', :instructor => '陳永富').first
Course.create( :name => '物理(一)', :instructor => '陳煜瑋', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物理(一)', :instructor => '陳煜瑋').first
Course.create( :name => '物理(一)', :instructor => '黃凱風', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物理(一)', :instructor => '黃凱風').first
Course.create( :name => '物理(一)', :instructor => '趙如蘋', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物理(一)', :instructor => '趙如蘋').first
Course.create( :name => '物理(一)', :instructor => '蘇蓉容', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物理(一)', :instructor => '蘇蓉容').first
Course.create( :name => '物理(二)', :instructor => '李威儀', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物理(二)', :instructor => '李威儀').first
Course.create( :name => '物理(二)', :instructor => '莊振益', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物理(二)', :instructor => '莊振益').first
Course.create( :name => '物理(二)', :instructor => '陳文雄', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物理(二)', :instructor => '陳文雄').first
Course.create( :name => '物理(二)', :instructor => '陳永富', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物理(二)', :instructor => '陳永富').first
Course.create( :name => '物理(二)', :instructor => '陳煜瑋', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物理(二)', :instructor => '陳煜瑋').first
Course.create( :name => '物理(二)', :instructor => '黃凱風', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物理(二)', :instructor => '黃凱風').first
Course.create( :name => '物理實驗(一)', :instructor => '物理實驗助教', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物理實驗(一)', :instructor => '物理實驗助教').first
Course.create( :name => '物理實驗(二)', :instructor => '物理實驗助教', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '物理實驗(二)', :instructor => '物理實驗助教').first
Course.create( :name => '計算機科學概論', :instructor => '胡毓志', :grade => 1, :description => '英文授課' ) unless Course.where(:name => '計算機科學概論', :instructor => '胡毓志').first
Course.create( :name => '計算機科學概論', :instructor => '蔡淳仁', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '計算機科學概論', :instructor => '蔡淳仁').first
Course.create( :name => '計算機概論與程式設計', :instructor => '王才沛', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '計算機概論與程式設計', :instructor => '王才沛').first
Course.create( :name => '計算機概論與程式設計', :instructor => '胡毓志', :grade => 1, :description => '大一必修，英文授課' ) unless Course.where(:name => '計算機概論與程式設計', :instructor => '胡毓志').first
Course.create( :name => '計算機概論與程式設計', :instructor => '孫春在', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '計算機概論與程式設計', :instructor => '孫春在').first
Course.create( :name => '計算機概論與程式設計', :instructor => '黃問泙', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '計算機概論與程式設計', :instructor => '黃問泙').first
Course.create( :name => '計算機概論與程式設計', :instructor => '蔡文能', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '計算機概論與程式設計', :instructor => '蔡文能').first
Course.create( :name => '計算機概論與程式設計', :instructor => '蕭旭峰', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '計算機概論與程式設計', :instructor => '蕭旭峰').first
Course.create( :name => '微積分(一)', :instructor => '王夏聲', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '微積分(一)', :instructor => '王夏聲').first
Course.create( :name => '微積分(一)', :instructor => '吳金典', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '微積分(一)', :instructor => '吳金典').first
Course.create( :name => '微積分(一)', :instructor => '吳培元', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '微積分(一)', :instructor => '吳培元').first
Course.create( :name => '微積分(一)', :instructor => '李勇達', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '微積分(一)', :instructor => '李勇達').first
Course.create( :name => '微積分(一)', :instructor => '翁志文', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '微積分(一)', :instructor => '翁志文').first
Course.create( :name => '微積分(一)', :instructor => '符麥克', :grade => 1, :description => '大一必修，英文授課' ) unless Course.where(:name => '微積分(一)', :instructor => '符麥克').first
Course.create( :name => '微積分(一)', :instructor => '許義容', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '微積分(一)', :instructor => '許義容').first
Course.create( :name => '微積分(二)', :instructor => '王夏聲', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '微積分(二)', :instructor => '王夏聲').first
Course.create( :name => '微積分(二)', :instructor => '吳金典', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '微積分(二)', :instructor => '吳金典').first
Course.create( :name => '微積分(二)', :instructor => '吳培元', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '微積分(二)', :instructor => '吳培元').first
Course.create( :name => '微積分(二)', :instructor => '李勇達', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '微積分(二)', :instructor => '李勇達').first
Course.create( :name => '微積分(二)', :instructor => '林武雄', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '微積分(二)', :instructor => '林武雄').first
Course.create( :name => '微積分(二)', :instructor => '翁志文', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '微積分(二)', :instructor => '翁志文').first
Course.create( :name => '微積分(二)', :instructor => '符麥克', :grade => 1, :description => '大一必修，英文授課' ) unless Course.where(:name => '微積分(二)', :instructor => '符麥克').first
Course.create( :name => '微積分(二)', :instructor => '許義容', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '微積分(二)', :instructor => '許義容').first
Course.create( :name => '數位電路設計', :instructor => '單智君', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '數位電路設計', :instructor => '單智君').first
Course.create( :name => '線性代數', :instructor => '易志偉', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '線性代數', :instructor => '易志偉').first
Course.create( :name => '線性代數', :instructor => '林源倍', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '線性代數', :instructor => '林源倍').first
Course.create( :name => '線性代數', :instructor => '莊榮宏', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '線性代數', :instructor => '莊榮宏').first
Course.create( :name => '線性代數', :instructor => '莫詩台方', :grade => 1, :description => '大一必修，英文授課' ) unless Course.where(:name => '線性代數', :instructor => '莫詩台方').first
Course.create( :name => '線性代數', :instructor => '陳永昇', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '線性代數', :instructor => '陳永昇').first
Course.create( :name => '線性代數', :instructor => '劉啟民', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '線性代數', :instructor => '劉啟民').first
Course.create( :name => '線性代數', :instructor => '蕭子健', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '線性代數', :instructor => '蕭子健').first
Course.create( :name => '線性代數', :instructor => '薛元澤', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '線性代數', :instructor => '薛元澤').first
Course.create( :name => '線性代數', :instructor => '譚建民', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '線性代數', :instructor => '譚建民').first
Course.create( :name => '離散數學', :instructor => '李素瑛', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '離散數學', :instructor => '李素瑛').first
Course.create( :name => '離散數學', :instructor => '易志偉', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '離散數學', :instructor => '易志偉').first
Course.create( :name => '離散數學', :instructor => '張立平', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '離散數學', :instructor => '張立平').first
Course.create( :name => '離散數學', :instructor => '陳玲慧', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '離散數學', :instructor => '陳玲慧').first
Course.create( :name => '離散數學', :instructor => '黃廷祿', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '離散數學', :instructor => '黃廷祿').first
Course.create( :name => '離散數學', :instructor => '黃問泙', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '離散數學', :instructor => '黃問泙').first
Course.create( :name => '離散數學', :instructor => '楊武', :grade => 1, :description => '大一必修' ) unless Course.where(:name => '離散數學', :instructor => '楊武').first
Course.create( :name => '訊號與系統', :instructor => '王忠炫', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '訊號與系統', :instructor => '王忠炫').first
Course.create( :name => '訊號與系統', :instructor => '張文輝', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '訊號與系統', :instructor => '張文輝').first
Course.create( :name => '訊號與系統', :instructor => '張錫嘉', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '訊號與系統', :instructor => '張錫嘉').first
Course.create( :name => '訊號與系統', :instructor => '黃經堯', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '訊號與系統', :instructor => '黃經堯').first
Course.create( :name => '訊號與系統', :instructor => '楊家驤', :grade => 2, :description => '大二必修，英文授課' ) unless Course.where(:name => '訊號與系統', :instructor => '楊家驤').first
Course.create( :name => '訊號與系統', :instructor => '劉啟民', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '訊號與系統', :instructor => '劉啟民').first
Course.create( :name => '訊號與系統', :instructor => '蔡尚澕', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '訊號與系統', :instructor => '蔡尚澕').first
Course.create( :name => '訊號與系統', :instructor => '蕭子健', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '訊號與系統', :instructor => '蕭子健').first
Course.create( :name => '訊號與系統', :instructor => '謝世福', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '訊號與系統', :instructor => '謝世福').first
Course.create( :name => '微分方程', :instructor => '王忠炫', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '微分方程', :instructor => '王忠炫').first
Course.create( :name => '微分方程', :instructor => '林心宇', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '微分方程', :instructor => '林心宇').first
Course.create( :name => '微分方程', :instructor => '林文杰', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '微分方程', :instructor => '林文杰').first
Course.create( :name => '微分方程', :instructor => '林志青', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '微分方程', :instructor => '林志青').first
Course.create( :name => '微分方程', :instructor => '梁耀文', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '微分方程', :instructor => '梁耀文').first
Course.create( :name => '微分方程', :instructor => '陸曉峰', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '微分方程', :instructor => '陸曉峰').first
Course.create( :name => '微分方程', :instructor => '楊春美', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '微分方程', :instructor => '楊春美').first
Course.create( :name => '微分方程', :instructor => '蔡淳仁', :grade => 2, :description => '大二必修，英文授課' ) unless Course.where(:name => '微分方程', :instructor => '蔡淳仁').first
Course.create( :name => '微分方程', :instructor => '霍斯科', :grade => 2, :description => '大二必修，英文授課' ) unless Course.where(:name => '微分方程', :instructor => '霍斯科').first
Course.create( :name => '電子實驗(一)', :instructor => '電子實驗助教', :grade => 2, :description => '大二必修，英文授課' ) unless Course.where(:name => '電子實驗(一)', :instructor => '電子實驗助教').first
Course.create( :name => '電子實驗(二)', :instructor => '電子實驗助教', :grade => 2, :description => '大二必修，英文授課' ) unless Course.where(:name => '電子實驗(二)', :instructor => '電子實驗助教').first
Course.create( :name => '電子學(一)', :instructor => '王毓駒', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '電子學(一)', :instructor => '王毓駒').first
Course.create( :name => '電子學(一)', :instructor => '莊紹勳', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '電子學(一)', :instructor => '莊紹勳').first
Course.create( :name => '電子學(一)', :instructor => '陳龍英', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '電子學(一)', :instructor => '陳龍英').first
Course.create( :name => '電子學(一)', :instructor => '陳巍仁', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '電子學(一)', :instructor => '陳巍仁').first
Course.create( :name => '電子學(二)', :instructor => '冉曉雯', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '電子學(二)', :instructor => '冉曉雯').first
Course.create( :name => '電子學(二)', :instructor => '洪崇智', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '電子學(二)', :instructor => '洪崇智').first
Course.create( :name => '電子學(二)', :instructor => '莊景德', :grade => 2, :description => '大二必修，英文授課' ) unless Course.where(:name => '電子學(二)', :instructor => '莊景德').first
Course.create( :name => '電子學(二)', :instructor => '陳龍英', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '電子學(二)', :instructor => '陳龍英').first
Course.create( :name => '電路學', :instructor => '李育民', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '電路學', :instructor => '李育民').first
Course.create( :name => '電路學', :instructor => '周復芳', :grade => 2, :description => '大二必修，英文授課' ) unless Course.where(:name => '電路學', :instructor => '周復芳').first
Course.create( :name => '電路學', :instructor => '陳永平', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '電路學', :instructor => '陳永平').first
Course.create( :name => '電路學', :instructor => '趙昌博', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '電路學', :instructor => '趙昌博').first
Course.create( :name => '電路學', :instructor => '謝世福', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '電路學', :instructor => '謝世福').first
Course.create( :name => '電路學', :instructor => '羅佩禎', :grade => 2, :description => '大二必修，英文授課' ) unless Course.where(:name => '電路學', :instructor => '羅佩禎').first
Course.create( :name => '數位電路實驗', :instructor => '林正中', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '數位電路實驗', :instructor => '林正中').first
Course.create( :name => '數位電路實驗', :instructor => '林進燈', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '數位電路實驗', :instructor => '林進燈').first
Course.create( :name => '數位電路實驗', :instructor => '范倫達', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '數位電路實驗', :instructor => '范倫達').first
Course.create( :name => '數位電路實驗', :instructor => '許騰尹', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '數位電路實驗', :instructor => '許騰尹').first
Course.create( :name => '數位電路實驗', :instructor => '陳健', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '數位電路實驗', :instructor => '陳健').first
Course.create( :name => '數位電路實驗', :instructor => '單智君', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '數位電路實驗', :instructor => '單智君').first
Course.create( :name => '複變函數', :instructor => '林清安', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '複變函數', :instructor => '林清安').first
Course.create( :name => '複變函數', :instructor => '林聖迪', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '複變函數', :instructor => '林聖迪').first
Course.create( :name => '複變函數', :instructor => '陳永平', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '複變函數', :instructor => '陳永平').first
Course.create( :name => '複變函數', :instructor => '歐陽盟', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '複變函數', :instructor => '歐陽盟').first
Course.create( :name => '複變函數', :instructor => '霍斯科', :grade => 2, :description => '大二必修，英文授課' ) unless Course.where(:name => '複變函數', :instructor => '霍斯科').first
Course.create( :name => '機率', :instructor => '吳炳飛', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '機率', :instructor => '吳炳飛').first
Course.create( :name => '機率', :instructor => '林盈達', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '機率', :instructor => '林盈達').first
Course.create( :name => '機率', :instructor => '高榮鴻', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '機率', :instructor => '高榮鴻').first
Course.create( :name => '機率', :instructor => '張仲儒', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '機率', :instructor => '張仲儒').first
Course.create( :name => '機率', :instructor => '張明峰', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '機率', :instructor => '張明峰').first
Course.create( :name => '機率', :instructor => '莫詩台方', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '機率', :instructor => '莫詩台方').first
Course.create( :name => '機率', :instructor => '陳稔', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '機率', :instructor => '陳稔').first
Course.create( :name => '機率', :instructor => '陳穎平', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '機率', :instructor => '陳穎平').first
Course.create( :name => '機率', :instructor => '彭文孝', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '機率', :instructor => '彭文孝').first
Course.create( :name => '機率', :instructor => '曾文貴', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '機率', :instructor => '曾文貴').first
Course.create( :name => '機率', :instructor => '曾建超', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '機率', :instructor => '曾建超').first
Course.create( :name => '機率', :instructor => '劉啟民', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '機率', :instructor => '劉啟民').first
Course.create( :name => '機率', :instructor => '蔡文祥', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '機率', :instructor => '蔡文祥').first
Course.create( :name => '機率', :instructor => '簡榮宏', :grade => 2, :description => '大二必修' ) unless Course.where(:name => '機率', :instructor => '簡榮宏').first
Course.create( :name => '人工智慧概論', :instructor => '王才沛', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '人工智慧概論', :instructor => '王才沛').first
Course.create( :name => '人工智慧概論', :instructor => '李嘉晃', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '人工智慧概論', :instructor => '李嘉晃').first
Course.create( :name => '人工智慧概論', :instructor => '孫春在', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '人工智慧概論', :instructor => '孫春在').first
Course.create( :name => '人工智慧概論', :instructor => '陳穎平', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '人工智慧概論', :instructor => '陳穎平').first
Course.create( :name => '半導體元件物理', :instructor => '崔秉鉞', :grade => 3, :description => '元件組課程、英文授課' ) unless Course.where(:name => '半導體元件物理', :instructor => '崔秉鉞').first
Course.create( :name => '半導體元件物理', :instructor => '陳冠能', :grade => 3, :description => '元件組課程、英文授課' ) unless Course.where(:name => '半導體元件物理', :instructor => '陳冠能').first
Course.create( :name => '正規語言概論', :instructor => '陳榮傑', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '正規語言概論', :instructor => '陳榮傑').first
Course.create( :name => '正規語言概論', :instructor => '陳穎平', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '正規語言概論', :instructor => '陳穎平').first
Course.create( :name => '正規語言概論', :instructor => '曾文貴', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '正規語言概論', :instructor => '曾文貴').first
Course.create( :name => '正規語言概論', :instructor => '黃廷祿', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '正規語言概論', :instructor => '黃廷祿').first
Course.create( :name => '正規語言概論', :instructor => '黃俊龍', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '正規語言概論', :instructor => '黃俊龍').first
Course.create( :name => '正規語言概論', :instructor => '楊武', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '正規語言概論', :instructor => '楊武').first
Course.create( :name => '正規語言概論', :instructor => '蔡文祥', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '正規語言概論', :instructor => '蔡文祥').first
Course.create( :name => '光子學(二)', :instructor => '林怡欣', :grade => 3, :description => '元件組課程' ) unless Course.where(:name => '光子學(二)', :instructor => '林怡欣').first
Course.create( :name => '作業系統概論', :instructor => '王協源', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '作業系統概論', :instructor => '王協源').first
Course.create( :name => '作業系統概論', :instructor => '吳育松', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '作業系統概論', :instructor => '吳育松').first
Course.create( :name => '作業系統概論', :instructor => '林奕成', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '作業系統概論', :instructor => '林奕成').first
Course.create( :name => '作業系統概論', :instructor => '林盈達', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '作業系統概論', :instructor => '林盈達').first
Course.create( :name => '作業系統概論', :instructor => '柯皓仁', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '作業系統概論', :instructor => '柯皓仁').first
Course.create( :name => '作業系統概論', :instructor => '袁賢銘', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '作業系統概論', :instructor => '袁賢銘').first
Course.create( :name => '作業系統概論', :instructor => '張力平', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '作業系統概論', :instructor => '張力平').first
Course.create( :name => '作業系統概論', :instructor => '黃世昆', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '作業系統概論', :instructor => '黃世昆').first
Course.create( :name => '作業系統概論', :instructor => '蔡文錦', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '作業系統概論', :instructor => '蔡文錦').first
Course.create( :name => '作業系統概論', :instructor => '謝續平', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '作業系統概論', :instructor => '謝續平').first
Course.create( :name => '計算機系統管理', :instructor => '系計中助教', :grade => 3, :description => '無' ) unless Course.where(:name => '計算機系統管理', :instructor => '系計中助教').first
Course.create( :name => '計算機系統管理', :instructor => '黃懷陞', :grade => 3, :description => '無' ) unless Course.where(:name => '計算機系統管理', :instructor => '黃懷陞').first
Course.create( :name => '計算機組織', :instructor => '李毅郎', :grade => 3, :description => '電路、資訊組課程' ) unless Course.where(:name => '計算機組織', :instructor => '李毅郎').first
Course.create( :name => '計算機組織', :instructor => '徐慰中', :grade => 3, :description => '電路、資訊組課程' ) unless Course.where(:name => '計算機組織', :instructor => '徐慰中').first
Course.create( :name => '計算機組織', :instructor => '張添烜', :grade => 3, :description => '電路、資訊組課程' ) unless Course.where(:name => '計算機組織', :instructor => '張添烜').first
Course.create( :name => '計算機組織', :instructor => '張瑞川', :grade => 3, :description => '電路、資訊組課程' ) unless Course.where(:name => '計算機組織', :instructor => '張瑞川').first
Course.create( :name => '計算機組織', :instructor => '陳添福', :grade => 3, :description => '電路、資訊組課程' ) unless Course.where(:name => '計算機組織', :instructor => '陳添福').first
Course.create( :name => '計算機組織', :instructor => '蔡文錦', :grade => 3, :description => '電路、資訊組課程' ) unless Course.where(:name => '計算機組織', :instructor => '蔡文錦').first
Course.create( :name => '計算機圖學概論', :instructor => '林奕成', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '計算機圖學概論', :instructor => '林奕成').first
Course.create( :name => '計算機圖學概論', :instructor => '林盈達', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '計算機圖學概論', :instructor => '林盈達').first
Course.create( :name => '計算機圖學概論', :instructor => '施仁忠', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '計算機圖學概論', :instructor => '施仁忠').first
Course.create( :name => '計算機圖學概論', :instructor => '莊榮宏', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '計算機圖學概論', :instructor => '莊榮宏').first
Course.create( :name => '計算機網路概論', :instructor => '謝續平', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '計算機網路概論', :instructor => '謝續平').first
Course.create( :name => '計算機網路管理', :instructor => '系計中助教', :grade => 3, :description => '無' ) unless Course.where(:name => '計算機網路管理', :instructor => '系計中助教').first
Course.create( :name => '計算機網路管理', :instructor => '陳穎平', :grade => 3, :description => '無' ) unless Course.where(:name => '計算機網路管理', :instructor => '陳穎平').first
Course.create( :name => '計算機網路管理', :instructor => '黃懷陞', :grade => 3, :description => '無' ) unless Course.where(:name => '計算機網路管理', :instructor => '黃懷陞').first
Course.create( :name => '密碼學概論', :instructor => '陳玲慧', :grade => 3, :description => '無' ) unless Course.where(:name => '密碼學概論', :instructor => '陳玲慧').first
Course.create( :name => '密碼學概論', :instructor => '陳榮傑', :grade => 3, :description => '無' ) unless Course.where(:name => '密碼學概論', :instructor => '陳榮傑').first
Course.create( :name => '組合語言與系統程式', :instructor => '黃世強', :grade => 3, :description => '英文授課' ) unless Course.where(:name => '組合語言與系統程式', :instructor => '黃世強').first
Course.create( :name => '通訊原理', :instructor => '林大衛', :grade => 3, :description => '系統組課程' ) unless Course.where(:name => '通訊原理', :instructor => '林大衛').first
Course.create( :name => '通訊原理', :instructor => '桑梓賢', :grade => 3, :description => '系統組課程' ) unless Course.where(:name => '通訊原理', :instructor => '桑梓賢').first
Course.create( :name => '通訊原理', :instructor => '劉志尉', :grade => 3, :description => '系統組課程' ) unless Course.where(:name => '通訊原理', :instructor => '劉志尉').first
Course.create( :name => '嵌入式系統技術實驗', :instructor => '郭峻因', :grade => 3, :description => '無' ) unless Course.where(:name => '嵌入式系統技術實驗', :instructor => '郭峻因').first
Course.create( :name => '嵌入式系統概論', :instructor => '陳耀宗', :grade => 3, :description => '無' ) unless Course.where(:name => '嵌入式系統概論', :instructor => '陳耀宗').first
Course.create( :name => '無線網路概論', :instructor => '曾建超', :grade => 3, :description => '無' ) unless Course.where(:name => '無線網路概論', :instructor => '曾建超').first
Course.create( :name => '無線網路概論', :instructor => '趙禧綠', :grade => 3, :description => '無' ) unless Course.where(:name => '無線網路概論', :instructor => '趙禧綠').first
Course.create( :name => '程式語言', :instructor => '陳耀宗', :grade => 3, :description => '無' ) unless Course.where(:name => '程式語言', :instructor => '陳耀宗').first
Course.create( :name => '程式語言', :instructor => '黃世強', :grade => 3, :description => '無' ) unless Course.where(:name => '程式語言', :instructor => '黃世強').first
Course.create( :name => '超大型積體電路設計導論', :instructor => '李鎮宜', :grade => 3, :description => '電路組課程' ) unless Course.where(:name => '超大型積體電路設計導論', :instructor => '李鎮宜').first
Course.create( :name => '超大型積體電路設計導論', :instructor => '張添烜', :grade => 3, :description => '電路組課程' ) unless Course.where(:name => '超大型積體電路設計導論', :instructor => '張添烜').first
Course.create( :name => '量子力學導論', :instructor => '李建平', :grade => 3, :description => '元件組課程' ) unless Course.where(:name => '量子力學導論', :instructor => '李建平').first
Course.create( :name => '微處理機系統實驗', :instructor => '林正中', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '微處理機系統實驗', :instructor => '林正中').first
Course.create( :name => '微算機原理與實驗', :instructor => '王逸如', :grade => 3, :description => '電路、系統組課程' ) unless Course.where(:name => '微算機原理與實驗', :instructor => '王逸如').first
Course.create( :name => '資料庫系統概論', :instructor => '李素瑛', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '資料庫系統概論', :instructor => '李素瑛').first
Course.create( :name => '資料庫系統概論', :instructor => '英家慶', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '資料庫系統概論', :instructor => '英家慶').first
Course.create( :name => '資料結構', :instructor => '李素瑛', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '資料結構', :instructor => '李素瑛').first
Course.create( :name => '資料結構', :instructor => '彭文志', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '資料結構', :instructor => '彭文志').first
Course.create( :name => '電子設計自動化概論', :instructor => '江蕙如', :grade => 3, :description => '電路組課程' ) unless Course.where(:name => '電子設計自動化概論', :instructor => '江蕙如').first
Course.create( :name => '電磁學(一)', :instructor => '鍾世忠', :grade => 3, :description => '元件、電路、系統組課程' ) unless Course.where(:name => '電磁學(一)', :instructor => '鍾世忠').first
Course.create( :name => '電磁學(二)', :instructor => '鍾世忠', :grade => 3, :description => '元件組課程' ) unless Course.where(:name => '電磁學(二)', :instructor => '鍾世忠').first
Course.create( :name => '圖形識別概論', :instructor => '王才沛', :grade => 3, :description => '無' ) unless Course.where(:name => '圖形識別概論', :instructor => '王才沛').first
Course.create( :name => '演算法概論', :instructor => '陳健', :grade => 3, :description => '資訊組課程，英文授課' ) unless Course.where(:name => '演算法概論', :instructor => '陳健').first
Course.create( :name => '網路程式設計概論', :instructor => '王協源', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '網路程式設計概論', :instructor => '王協源').first
Course.create( :name => '網路程式設計概論', :instructor => '吳毅成', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '網路程式設計概論', :instructor => '吳毅成').first
Course.create( :name => '網路程式設計概論', :instructor => '林盈達', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '網路程式設計概論', :instructor => '林盈達').first
Course.create( :name => '影像處理概論', :instructor => '莊仁輝', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '影像處理概論', :instructor => '莊仁輝').first
Course.create( :name => '數位訊號處理概論', :instructor => '王聖智', :grade => 3, :description => '系統組課程' ) unless Course.where(:name => '數位訊號處理概論', :instructor => '王聖智').first
Course.create( :name => '數位訊號處理概論', :instructor => '莊仁輝', :grade => 3, :description => '系統組課程' ) unless Course.where(:name => '數位訊號處理概論', :instructor => '莊仁輝').first
Course.create( :name => '數值分析', :instructor => '謝世福', :grade => 3, :description => '無' ) unless Course.where(:name => '數值分析', :instructor => '謝世福').first
Course.create( :name => '數值方法', :instructor => '林文杰', :grade => 3, :description => '無' ) unless Course.where(:name => '數值方法', :instructor => '林文杰').first
Course.create( :name => '數值方法', :instructor => '林志青', :grade => 3, :description => '無' ) unless Course.where(:name => '數值方法', :instructor => '林志青').first
Course.create( :name => '數據通訊', :instructor => '李程輝', :grade => 3, :description => '系統組課程' ) unless Course.where(:name => '數據通訊', :instructor => '李程輝').first
Course.create( :name => '線性控制系統', :instructor => '吳炳飛', :grade => 3, :description => '無' ) unless Course.where(:name => '線性控制系統', :instructor => '吳炳飛').first
Course.create( :name => '編譯器設計概論', :instructor => '徐慰中', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '編譯器設計概論', :instructor => '徐慰中').first
Course.create( :name => '編譯器設計概論', :instructor => '游逸平', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '編譯器設計概論', :instructor => '游逸平').first
Course.create( :name => '編譯器設計概論', :instructor => '楊武', :grade => 3, :description => '資訊組課程' ) unless Course.where(:name => '編譯器設計概論', :instructor => '楊武').first
Course.create( :name => '類比積體電路導論', :instructor => '吳重雨', :grade => 3, :description => '電路組課程' ) unless Course.where(:name => '類比積體電路導論', :instructor => '吳重雨').first
Course.create( :name => 'RFID概論', :instructor => '謝錫興', :grade => 4, :description => '無' ) unless Course.where(:name => 'RFID概論', :instructor => '謝錫興').first
Course.create( :name => 'VLSI與系統晶片設計概論', :instructor => '范倫達', :grade => 4, :description => '無' ) unless Course.where(:name => 'VLSI與系統晶片設計概論', :instructor => '范倫達').first
Course.create( :name => 'VLSI與系統晶片設計概論', :instructor => '許騰尹', :grade => 4, :description => '無' ) unless Course.where(:name => 'VLSI與系統晶片設計概論', :instructor => '許騰尹').first
Course.create( :name => '人工智慧', :instructor => '陳穎平', :grade => 4, :description => '無' ) unless Course.where(:name => '人工智慧', :instructor => '陳穎平').first
Course.create( :name => '分群法', :instructor => '林志青', :grade => 4, :description => '無' ) unless Course.where(:name => '分群法', :instructor => '林志青').first
Course.create( :name => '正規語言', :instructor => '陳穎平', :grade => 4, :description => '無' ) unless Course.where(:name => '正規語言', :instructor => '陳穎平').first
Course.create( :name => '多媒體資訊系統概論', :instructor => '蕭旭峰', :grade => 4, :description => '無' ) unless Course.where(:name => '多媒體資訊系統概論', :instructor => '蕭旭峰').first
Course.create( :name => '作業系統', :instructor => '袁賢銘', :grade => 4, :description => '無' ) unless Course.where(:name => '作業系統', :instructor => '袁賢銘').first
Course.create( :name => '計算機架構', :instructor => '鍾崇斌', :grade => 4, :description => '英文授課' ) unless Course.where(:name => '計算機架構', :instructor => '鍾崇斌').first
Course.create( :name => '計算機科學概論', :instructor => '胡毓志', :grade => 4, :description => '無' ) unless Course.where(:name => '計算機科學概論', :instructor => '胡毓志').first
Course.create( :name => '計算機科學概論', :instructor => '孫春在', :grade => 4, :description => '無' ) unless Course.where(:name => '計算機科學概論', :instructor => '孫春在').first
Course.create( :name => '計算機科學概論', :instructor => '荊宇泰', :grade => 4, :description => '無' ) unless Course.where(:name => '計算機科學概論', :instructor => '荊宇泰').first
Course.create( :name => '計算機科學概論', :instructor => '陳永昇', :grade => 4, :description => '無' ) unless Course.where(:name => '計算機科學概論', :instructor => '陳永昇').first
Course.create( :name => '計算機科學概論', :instructor => '蔡文能', :grade => 4, :description => '無' ) unless Course.where(:name => '計算機科學概論', :instructor => '蔡文能').first
Course.create( :name => '計算機科學概論', :instructor => '蔡淳仁', :grade => 4, :description => '無' ) unless Course.where(:name => '計算機科學概論', :instructor => '蔡淳仁').first
Course.create( :name => '計算機結構', :instructor => '劉志尉', :grade => 4, :description => '無' ) unless Course.where(:name => '計算機結構', :instructor => '劉志尉').first
Course.create( :name => '計算機網路實驗', :instructor => '王協源', :grade => 4, :description => '無' ) unless Course.where(:name => '計算機網路實驗', :instructor => '王協源').first
Course.create( :name => '區域網路與通訊原理', :instructor => '王國禎', :grade => 4, :description => '無' ) unless Course.where(:name => '區域網路與通訊原理', :instructor => '王國禎').first
Course.create( :name => '區域網路與通訊原理', :instructor => '陳穎平', :grade => 4, :description => '無' ) unless Course.where(:name => '區域網路與通訊原理', :instructor => '陳穎平').first
Course.create( :name => '區域網路與通訊原理', :instructor => '趙禧綠', :grade => 4, :description => '無' ) unless Course.where(:name => '區域網路與通訊原理', :instructor => '趙禧綠').first
Course.create( :name => '組合語言與系統程式', :instructor => '林正中', :grade => 4, :description => '無' ) unless Course.where(:name => '組合語言與系統程式', :instructor => '林正中').first
Course.create( :name => '組合語言與系統程式', :instructor => '柯皓仁', :grade => 4, :description => '無' ) unless Course.where(:name => '組合語言與系統程式', :instructor => '柯皓仁').first
Course.create( :name => '組合語言與系統程式', :instructor => '陳永昇', :grade => 4, :description => '無' ) unless Course.where(:name => '組合語言與系統程式', :instructor => '陳永昇').first
Course.create( :name => '組合語言與系統程式', :instructor => '蔡文錦', :grade => 4, :description => '無' ) unless Course.where(:name => '組合語言與系統程式', :instructor => '蔡文錦').first
Course.create( :name => '組合數學', :instructor => '張明峰', :grade => 4, :description => '無' ) unless Course.where(:name => '組合數學', :instructor => '張明峰').first
Course.create( :name => '軟體工程概論', :instructor => '王豐堅', :grade => 4, :description => '無' ) unless Course.where(:name => '軟體工程概論', :instructor => '王豐堅').first
Course.create( :name => '軟體定義網路', :instructor => '王協源', :grade => 4, :description => '無' ) unless Course.where(:name => '軟體定義網路', :instructor => '王協源').first
Course.create( :name => '嵌入式系統設計', :instructor => '鍾崇斌', :grade => 4, :description => '無' ) unless Course.where(:name => '嵌入式系統設計', :instructor => '鍾崇斌').first
Course.create( :name => '程式語言', :instructor => '陳耀宗', :grade => 4, :description => '無' ) unless Course.where(:name => '程式語言', :instructor => '陳耀宗').first
Course.create( :name => '程式語言', :instructor => '游逸平', :grade => 4, :description => '無' ) unless Course.where(:name => '程式語言', :instructor => '游逸平').first
Course.create( :name => '程式語言', :instructor => '黃世強', :grade => 4, :description => '無' ) unless Course.where(:name => '程式語言', :instructor => '黃世強').first
Course.create( :name => '程式語言', :instructor => '黃問泙', :grade => 4, :description => '無' ) unless Course.where(:name => '程式語言', :instructor => '黃問泙').first
Course.create( :name => '程式語言', :instructor => '蔡文錦', :grade => 4, :description => '無' ) unless Course.where(:name => '程式語言', :instructor => '蔡文錦').first
Course.create( :name => '資料探勘', :instructor => '曾新穆', :grade => 4, :description => '無' ) unless Course.where(:name => '資料探勘', :instructor => '曾新穆').first
Course.create( :name => '電腦安全概論', :instructor => '林盈達', :grade => 4, :description => '無' ) unless Course.where(:name => '電腦安全概論', :instructor => '林盈達').first
Course.create( :name => '電腦安全概論', :instructor => '曾文貴', :grade => 4, :description => '無' ) unless Course.where(:name => '電腦安全概論', :instructor => '曾文貴').first
Course.create( :name => '電腦安全概論', :instructor => '謝續平', :grade => 4, :description => '無' ) unless Course.where(:name => '電腦安全概論', :instructor => '謝續平').first
Course.create( :name => '圖形識別', :instructor => '王才沛', :grade => 4, :description => '無' ) unless Course.where(:name => '圖形識別', :instructor => '王才沛').first
Course.create( :name => '演化計算', :instructor => '陳穎平', :grade => 4, :description => '無' ) unless Course.where(:name => '演化計算', :instructor => '陳穎平').first
Course.create( :name => '演算法', :instructor => '蔡錫鈞', :grade => 4, :description => '無' ) unless Course.where(:name => '演算法', :instructor => '蔡錫鈞').first
Course.create( :name => '演算法', :instructor => '譚建民', :grade => 4, :description => '無' ) unless Course.where(:name => '演算法', :instructor => '譚建民').first
Course.create( :name => '網路安全', :instructor => '邵家健', :grade => 4, :description => '無' ) unless Course.where(:name => '網路安全', :instructor => '邵家健').first
Course.create( :name => '網路安全', :instructor => '謝續平', :grade => 4, :description => '無' ) unless Course.where(:name => '網路安全', :instructor => '謝續平').first
Course.create( :name => '網路程式設計', :instructor => '吳毅成', :grade => 4, :description => '無' ) unless Course.where(:name => '網路程式設計', :instructor => '吳毅成').first
Course.create( :name => '網際網路規約', :instructor => '曾建超', :grade => 4, :description => '無' ) unless Course.where(:name => '網際網路規約', :instructor => '曾建超').first
Course.create( :name => '影像處理', :instructor => '王才沛', :grade => 4, :description => '無' ) unless Course.where(:name => '影像處理', :instructor => '王才沛').first
Course.create( :name => '數位電視系統設計', :instructor => '蔡文錦', :grade => 4, :description => '無' ) unless Course.where(:name => '數位電視系統設計', :instructor => '蔡文錦').first
Course.create( :name => '積體電路設計實驗', :instructor => '張添烜', :grade => 4, :description => '英文授課' ) unless Course.where(:name => '積體電路設計實驗', :instructor => '張添烜').first
Course.create( :name => '輸出入裝置與驅動程式設計', :instructor => '曹孝櫟', :grade => 4, :description => '無' ) unless Course.where(:name => '輸出入裝置與驅動程式設計', :instructor => '曹孝櫟').first
Course.create( :name => '中級日語會話', :instructor => '上條純惠', :grade => 5, :description => '無' ) unless Course.where(:name => '中級日語會話', :instructor => '上條純惠').first
Course.create( :name => '日文(一)', :instructor => '上條純惠', :grade => 5, :description => '無' ) unless Course.where(:name => '日文(一)', :instructor => '上條純惠').first
Course.create( :name => '日文(一)', :instructor => '周雅玲', :grade => 5, :description => '無' ) unless Course.where(:name => '日文(一)', :instructor => '周雅玲').first
Course.create( :name => '日文(一)', :instructor => '金想容', :grade => 5, :description => '無' ) unless Course.where(:name => '日文(一)', :instructor => '金想容').first
Course.create( :name => '日文(二)', :instructor => '上條純惠', :grade => 5, :description => '無' ) unless Course.where(:name => '日文(二)', :instructor => '上條純惠').first
Course.create( :name => '日文(三)', :instructor => '周雅玲', :grade => 5, :description => '無' ) unless Course.where(:name => '日文(三)', :instructor => '周雅玲').first
Course.create( :name => '日文(三)', :instructor => '武藤泰子', :grade => 5, :description => '無' ) unless Course.where(:name => '日文(三)', :instructor => '武藤泰子').first
Course.create( :name => '日文(三)', :instructor => '詹兆雯', :grade => 5, :description => '無' ) unless Course.where(:name => '日文(三)', :instructor => '詹兆雯').first
Course.create( :name => '日文(五)', :instructor => '周雅玲', :grade => 5, :description => '無' ) unless Course.where(:name => '日文(五)', :instructor => '周雅玲').first
Course.create( :name => '日文(五)', :instructor => '黃美卿', :grade => 5, :description => '無' ) unless Course.where(:name => '日文(五)', :instructor => '黃美卿').first
Course.create( :name => '日文(六)', :instructor => '周雅玲', :grade => 5, :description => '無' ) unless Course.where(:name => '日文(六)', :instructor => '周雅玲').first
Course.create( :name => '日文(六)', :instructor => '詹兆雯', :grade => 5, :description => '無' ) unless Course.where(:name => '日文(六)', :instructor => '詹兆雯').first
Course.create( :name => '日文(四)', :instructor => '周雅玲', :grade => 5, :description => '無' ) unless Course.where(:name => '日文(四)', :instructor => '周雅玲').first
Course.create( :name => '日文(四)', :instructor => '武藤泰子', :grade => 5, :description => '無' ) unless Course.where(:name => '日文(四)', :instructor => '武藤泰子').first
Course.create( :name => '日文(四)', :instructor => '徐佩伶', :grade => 5, :description => '老師已離開學校' ) unless Course.where(:name => '日文(四)', :instructor => '徐佩伶').first
Course.create( :name => '法文(一)', :instructor => '潘怡君', :grade => 5, :description => '無' ) unless Course.where(:name => '法文(一)', :instructor => '潘怡君').first
Course.create( :name => '英文閱讀', :instructor => '吳舜華', :grade => 5, :description => '無' ) unless Course.where(:name => '英文閱讀', :instructor => '吳舜華').first
Course.create( :name => '英文聽力訓練', :instructor => '吳思葦', :grade => 5, :description => '無' ) unless Course.where(:name => '英文聽力訓練', :instructor => '吳思葦').first
Course.create( :name => '進修英語一:聽力', :instructor => '闕郁軒', :grade => 5, :description => '無' ) unless Course.where(:name => '進修英語一:聽力', :instructor => '闕郁軒').first
Course.create( :name => '進修英語二:閱讀', :instructor => '林曉薇', :grade => 5, :description => '無' ) unless Course.where(:name => '進修英語二:閱讀', :instructor => '林曉薇').first
Course.create( :name => '進階口語訓練', :instructor => '楊芳盈', :grade => 5, :description => '無' ) unless Course.where(:name => '進階口語訓練', :instructor => '楊芳盈').first
Course.create( :name => '進階英文聽力', :instructor => '李寶莉', :grade => 5, :description => '這位老師現在只有開商用英文' ) unless Course.where(:name => '進階英文聽力', :instructor => '李寶莉').first
Course.create( :name => '進階英文聽力與討論', :instructor => '吳思葦', :grade => 5, :description => '無' ) unless Course.where(:name => '進階英文聽力與討論', :instructor => '吳思葦').first
Course.create( :name => '新聞英語', :instructor => '黃伊岑', :grade => 5, :description => '無' ) unless Course.where(:name => '新聞英語', :instructor => '黃伊岑').first
Course.create( :name => '德文(一)', :instructor => '楊燕詒', :grade => 5, :description => '無' ) unless Course.where(:name => '德文(一)', :instructor => '楊燕詒').first
Course.create( :name => '德文(二)', :instructor => '楊燕詒', :grade => 5, :description => '無' ) unless Course.where(:name => '德文(二)', :instructor => '楊燕詒').first
Course.create( :name => '德文(三)', :instructor => '楊燕詒', :grade => 5, :description => '無' ) unless Course.where(:name => '德文(三)', :instructor => '楊燕詒').first
Course.create( :name => '工程與專業倫理', :instructor => '楊台恩', :grade => 6, :description => '自然' ) unless Course.where(:name => '工程與專業倫理', :instructor => '楊台恩').first
Course.create( :name => '中國與東亞文明史', :instructor => '王瑞傑', :grade => 6, :description => '歷史/基礎' ) unless Course.where(:name => '中國與東亞文明史', :instructor => '王瑞傑').first
Course.create( :name => '中國與東亞文明史', :instructor => '張文昌', :grade => 6, :description => '歷史/基礎' ) unless Course.where(:name => '中國與東亞文明史', :instructor => '張文昌').first
Course.create( :name => '中國與東亞文明史', :instructor => '藍弘岳', :grade => 6, :description => '歷史/基礎' ) unless Course.where(:name => '中國與東亞文明史', :instructor => '藍弘岳').first
Course.create( :name => '心理學概論', :instructor => '梁瓊惠', :grade => 6, :description => '群己/基礎，不接受修讀過「心理學」或「心理學概論」同學修讀。' ) unless Course.where(:name => '心理學概論', :instructor => '梁瓊惠').first
Course.create( :name => '心理學概論', :instructor => '陳慧珍', :grade => 6, :description => '群己/基礎，不接受修讀過「心理學」或「心理學概論」同學修讀。' ) unless Course.where(:name => '心理學概論', :instructor => '陳慧珍').first
Course.create( :name => '文學經典:詩經', :instructor => '劉龍勳', :grade => 6, :description => '文化/基礎' ) unless Course.where(:name => '文學經典:詩經', :instructor => '劉龍勳').first
Course.create( :name => '文學與人生', :instructor => '王月秀', :grade => 6, :description => '文化/進階' ) unless Course.where(:name => '文學與人生', :instructor => '王月秀').first
Course.create( :name => '日本文化史', :instructor => '藍弘岳', :grade => 6, :description => '歷史' ) unless Course.where(:name => '日本文化史', :instructor => '藍弘岳').first
Course.create( :name => '日本現勢', :instructor => '楊永良', :grade => 6, :description => '公民/進階' ) unless Course.where(:name => '日本現勢', :instructor => '楊永良').first
Course.create( :name => '世界文明史', :instructor => '丁崑健', :grade => 6, :description => '歷史/基礎' ) unless Course.where(:name => '世界文明史', :instructor => '丁崑健').first
Course.create( :name => '世界文明史', :instructor => '陳仁姮', :grade => 6, :description => '歷史/基礎' ) unless Course.where(:name => '世界文明史', :instructor => '陳仁姮').first
Course.create( :name => '世界近代史', :instructor => '徐文路', :grade => 6, :description => '歷史/進階' ) unless Course.where(:name => '世界近代史', :instructor => '徐文路').first
Course.create( :name => '世界動漫史', :instructor => '王佩迪', :grade => 6, :description => '群己/進階' ) unless Course.where(:name => '世界動漫史', :instructor => '王佩迪').first
Course.create( :name => '古典音樂賞析─從巴洛克到現代音樂', :instructor => '謝明志', :grade => 6, :description => '文化/進階' ) unless Course.where(:name => '古典音樂賞析─從巴洛克到現代音樂', :instructor => '謝明志').first
Course.create( :name => '台灣史', :instructor => '張慧安', :grade => 6, :description => '歷史/基礎，不接受人社系及修讀過「台灣文化社會史」的同學修讀。' ) unless Course.where(:name => '台灣史', :instructor => '張慧安').first
Course.create( :name => '生命科學', :instructor => '陳曉青、陳文亮', :grade => 6, :description => '自然/基礎，不接受生科系、奈米學系同學修讀。' ) unless Course.where(:name => '生命科學', :instructor => '陳曉青、陳文亮').first
Course.create( :name => '生物資訊入門', :instructor => '黃慧玲', :grade => 6, :description => '自然' ) unless Course.where(:name => '生物資訊入門', :instructor => '黃慧玲').first
Course.create( :name => '企業經營通識講座', :instructor => '楊千', :grade => 6, :description => '群己' ) unless Course.where(:name => '企業經營通識講座', :instructor => '楊千').first
Course.create( :name => '伊斯蘭文明', :instructor => '趙錫麟', :grade => 6, :description => '歷史/進階' ) unless Course.where(:name => '伊斯蘭文明', :instructor => '趙錫麟').first
Course.create( :name => '先進科技與太空探索', :instructor => '陳大明', :grade => 6, :description => '自然' ) unless Course.where(:name => '先進科技與太空探索', :instructor => '陳大明').first
Course.create( :name => '光電科技概論', :instructor => '李柏璁', :grade => 6, :description => '自然' ) unless Course.where(:name => '光電科技概論', :instructor => '李柏璁').first
Course.create( :name => '全球化與兩岸關係', :instructor => '劉河北', :grade => 6, :description => '歷史/進階' ) unless Course.where(:name => '全球化與兩岸關係', :instructor => '劉河北').first
Course.create( :name => '全球音樂文化：宗教與儀式', :instructor => '高雅俐', :grade => 6, :description => '文化' ) unless Course.where(:name => '全球音樂文化：宗教與儀式', :instructor => '高雅俐').first
Course.create( :name => '向量分析', :instructor => '林琦焜', :grade => 6, :description => '無' ) unless Course.where(:name => '向量分析', :instructor => '林琦焜').first
Course.create( :name => '地球科學概論', :instructor => '黃心亮', :grade => 6, :description => '自然/基礎' ) unless Course.where(:name => '地球科學概論', :instructor => '黃心亮').first
Course.create( :name => '有線-無線網路技術整合與應用', :instructor => '謝俊齡', :grade => 6, :description => '無' ) unless Course.where(:name => '有線-無線網路技術整合與應用', :instructor => '謝俊齡').first
Course.create( :name => '批判性思考', :instructor => '徐金雲', :grade => 6, :description => '自然/進階' ) unless Course.where(:name => '批判性思考', :instructor => '徐金雲').first
Course.create( :name => '建築空間的形成：過去與現在', :instructor => '林秀芬', :grade => 6, :description => '文化' ) unless Course.where(:name => '建築空間的形成：過去與現在', :instructor => '林秀芬').first
Course.create( :name => '政治學', :instructor => '胡正光', :grade => 6, :description => '公民/基礎' ) unless Course.where(:name => '政治學', :instructor => '胡正光').first
Course.create( :name => '音樂概論', :instructor => '黃齡緹', :grade => 6, :description => '文化/基礎' ) unless Course.where(:name => '音樂概論', :instructor => '黃齡緹').first
Course.create( :name => '動漫文化與性別', :instructor => '王佩迪', :grade => 6, :description => '群己/進階' ) unless Course.where(:name => '動漫文化與性別', :instructor => '王佩迪').first
Course.create( :name => '御宅學', :instructor => '王佩迪', :grade => 6, :description => '群己/進階' ) unless Course.where(:name => '御宅學', :instructor => '王佩迪').first
Course.create( :name => '統計學', :instructor => '陳志榮', :grade => 6, :description => '無' ) unless Course.where(:name => '統計學', :instructor => '陳志榮').first
Course.create( :name => '統計學', :instructor => '彭南夫', :grade => 6, :description => '無' ) unless Course.where(:name => '統計學', :instructor => '彭南夫').first
Course.create( :name => '新馬克思主義與當代思潮', :instructor => '洪鐮德', :grade => 6, :description => '群己' ) unless Course.where(:name => '新馬克思主義與當代思潮', :instructor => '洪鐮德').first
Course.create( :name => '新聞學概論', :instructor => '蒯亮', :grade => 6, :description => '群己/進階' ) unless Course.where(:name => '新聞學概論', :instructor => '蒯亮').first
Course.create( :name => '當代世界:國際關係與組織', :instructor => '高佩珊', :grade => 6, :description => '必修' ) unless Course.where(:name => '當代世界:國際關係與組織', :instructor => '高佩珊').first
Course.create( :name => '當代世界:認同與文化', :instructor => '黃國清', :grade => 6, :description => '必修' ) unless Course.where(:name => '當代世界:認同與文化', :instructor => '黃國清').first
Course.create( :name => '當代世界:環境危機與生態永續', :instructor => '王從恕', :grade => 6, :description => '必修' ) unless Course.where(:name => '當代世界:環境危機與生態永續', :instructor => '王從恕').first
Course.create( :name => '當代世界:環境危機與生態永續', :instructor => '林高永', :grade => 6, :description => '必修' ) unless Course.where(:name => '當代世界:環境危機與生態永續', :instructor => '林高永').first
Course.create( :name => '經典通識教育講座', :instructor => '劉河北;洪惠冠', :grade => 6, :description => '公民/進階' ) unless Course.where(:name => '經典通識教育講座', :instructor => '劉河北;洪惠冠').first
Course.create( :name => '經濟學概論', :instructor => '譚經緯', :grade => 6, :description => '公民/基礎，不接受管理學院同學修讀。' ) unless Course.where(:name => '經濟學概論', :instructor => '譚經緯').first
Course.create( :name => '資訊素養與倫理', :instructor => '王美鴻', :grade => 6, :description => '公民/進階' ) unless Course.where(:name => '資訊素養與倫理', :instructor => '王美鴻').first
Course.create( :name => '道德推理', :instructor => '王冠生', :grade => 6, :description => '群己，老師不再開課' ) unless Course.where(:name => '道德推理', :instructor => '王冠生').first
Course.create( :name => '電玩藝術文化分析', :instructor => '梁世佑', :grade => 6, :description => '文化/進階' ) unless Course.where(:name => '電玩藝術文化分析', :instructor => '梁世佑').first
Course.create( :name => '網路與社會', :instructor => '李威霆', :grade => 6, :description => '群己' ) unless Course.where(:name => '網路與社會', :instructor => '李威霆').first
Course.create( :name => '數位文創原案發想及劇本寫作', :instructor => '許經夌', :grade => 6, :description => '文化/進階' ) unless Course.where(:name => '數位文創原案發想及劇本寫作', :instructor => '許經夌').first
Course.create( :name => '數位視覺文化', :instructor => '梁世佑', :grade => 6, :description => '文化/進階' ) unless Course.where(:name => '數位視覺文化', :instructor => '梁世佑').first
Course.create( :name => '憲法與政府體制', :instructor => '蘇子喬', :grade => 6, :description => '公民' ) unless Course.where(:name => '憲法與政府體制', :instructor => '蘇子喬').first
Course.create( :name => '戰後台灣環境運動史', :instructor => '徐文路', :grade => 6, :description => '歷史' ) unless Course.where(:name => '戰後台灣環境運動史', :instructor => '徐文路').first
Course.create( :name => '諾貝爾獎與二十世紀物理', :instructor => '黃凱風', :grade => 6, :description => '自然向度' ) unless Course.where(:name => '諾貝爾獎與二十世紀物理', :instructor => '黃凱風').first
Course.create( :name => '藝術概論', :instructor => '張武恭', :grade => 6, :description => '文化/基礎' ) unless Course.where(:name => '藝術概論', :instructor => '張武恭').first
Course.create( :name => '邏輯與思維', :instructor => '趙敏芝', :grade => 6, :description => '自然/基礎' ) unless Course.where(:name => '邏輯與思維', :instructor => '趙敏芝').first
